version: '3'
services:
  supabase:
    image: supabase/supabase
    ports:
      - "5432:5432"
      - "5431:5431"
    environment:
      - SUPABASE_URL=postgres://supabase@localhost:5432/supabase
      - SUPABASE_KEY=pokdmuwpqneuowaa
    networks:
      - supabase-network
    volumes:
      - supabase-data:/var/lib/postgresql/data
    restart: always

  node-app:
    build: .
    ports:
      - "3100:3000"
    depends_on:
      - supabase
    networks:
      - supabase-network
    restart: always

networks:
  supabase-network:
    driver: bridge

volumes:
  supabase-data:
